---
- hosts: arch

  vars:
      username: mandlm
      password: $6$hfdjshdfkajdsh$DRgmUOQfm9DnvSv.l.WuQJpextzBpX5BCbSncXTts5dHazvKRxj8qUYAjju2/AGZqKOt8PTLC7w9yRR68ZHCG1 
      dotfiles: "~/.dotfiles"

  become: yes

  roles:
    - user-account
    - sudo
    - dotfiles
    - git
    - tmux
    - zsh
    - neovim
    - vimwiki
    - tools
    - acpid
    - docker
    - wayland
    - aur-builder
    - zoom
    - git-flow
    - slack

  tasks:
    - name: Install common user applications
      package:
          name: "{{ item }}"
          state: latest
      loop:
        - element-desktop
        - firefox
        - keepassxc
        - nextcloud-client
        - signal-desktop
        - telegram-desktop
        - thunderbird
