---
- hosts: arch
  vars:
      username: mandlm
      password: $6$hfdjshdfkajdsh$DRgmUOQfm9DnvSv.l.WuQJpextzBpX5BCbSncXTts5dHazvKRxj8qUYAjju2/AGZqKOt8PTLC7w9yRR68ZHCG1 
      dotfiles: "~/.dotfiles"
  become: yes
  roles:
    - user-account
    - dotfiles
    - git
    - tmux
    - zsh
    - neovim
    - tools
