---
- hosts: wsl-debian
  vars:
      username: mandlm
      password: $6$hfdjshdfkajdsh$DRgmUOQfm9DnvSv.l.WuQJpextzBpX5BCbSncXTts5dHazvKRxj8qUYAjju2/AGZqKOt8PTLC7w9yRR68ZHCG1 
      dotfiles: "~/.dotfiles"
  become: yes
  gather_facts: no
  roles:
    - update-packages
    - user-account
    - github-auth
    - dotfiles
    - git
    - tmux
    - zsh
    - neovim
    - tools
