---
- hosts: wsl-debian
  vars:
      username: mandlm
      password: $6$hfdjshdfkajdsh$DRgmUOQfm9DnvSv.l.WuQJpextzBpX5BCbSncXTts5dHazvKRxj8qUYAjju2/AGZqKOt8PTLC7w9yRR68ZHCG1 
      dotfiles: "~/.dotfiles"
  become: yes
  roles:
    - update-packages
    - user-account
    # - github-auth
    - wsl-default-user
    - dotfiles
    - git
    - tmux
    - zsh
    - neovim-appimage
    - vimwiki
    - tools
    - dev-machine
    - pinentry-wsl
    - wsl-open
    - dockerd-wsl
    - dircolors-wsl
