---
- name: install packages
  package:
      name: "{{ item }}"
      state: latest
  loop:
    - xorg
    - xorg-server
    - xorg-xinit
    - xorg-xsetroot
    - xf86-video-intel
    - xf86-video-fbdev
    - sddm
    - i3-wm
    - i3status
    - dmenu
    - alacritty

- name: activate display manager
  systemd:
      name: sddm
      enabled: yes

- name: set keyboard layout
  command:
      cmd: localectl --no-convert set-x11-keymap de pc105 nodeadkeys
      creates: /etc/X11/xorg.conf.d/00-keyboard.conf
