---
- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  loop:
    - xorg
    - xorg-server
    - xorg-xinit
    - xorg-xsetroot
    - xf86-video-intel
    - xf86-video-fbdev
    - sddm
    - i3-wm
    - i3status
    - xautolock
    - i3lock
    - dmenu
    - alacritty
    - flameshot

- name: configure sddm
  ini_file:
    path: /etc/sddm.conf.d/uid.conf
    section: Users
    option: HideShells
    value: /usr/bin/nologin,/sbin/nologin,/bin/false
    mode: 0644
    create: yes

- name: activate display manager
  systemd:
    name: sddm
    enabled: yes

- name: set keyboard layout
  command:
    cmd: localectl --no-convert set-x11-keymap de pc105 nodeadkeys
    creates: /etc/X11/xorg.conf.d/00-keyboard.conf

- name: install i3 config
  become_user: "{{ account.name }}"
  copy:
    src: config/i3/config
    dest: "/home/{{ account.name }}/.config/i3/config"
    force: no

- name: install i3status config
  become_user: "{{ account.name }}"
  copy:
    src: config/i3status/config
    dest: "/home/{{ account.name }}/.config/i3status/config"
    force: yes
