---    
- name: install required packages
  package:
      name:
        - git
        - openssh
      state: latest

- name: clone dotfiles
  become_user: "{{ account.name }}"
  git:
      repo: git@github.com:mandlm/dotfiles.git
      dest: "{{ dotfiles }}"
      accept_hostkey: yes
      update: no

- name: ensure user/bin exists
  become_user: "{{ account.name }}"
  file:
      path: "/home/{{ account.name }}/bin"
      state: directory
      mode: "0744"

- name: install bin scripts
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/bin"
      cmd: ./install.sh
      creates: "{{ account.home }}/bin/wiki-sync"
