---
- name: install required packages
  package:
      name:
        - curl
        - zsh
      state: latest

- name: install zsh config
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/zsh"
      cmd: ./install.sh
      creates: "{{ account.home }}/.zshrc"
  
- name: install oh-my-zsh
  become_user: "{{ account.name }}"
  shell: 
      cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended --keep-zshrc"
      creates: "{{ account.home }}/.oh-my-zsh"

- name: change login shell to zsh
  user:
      name: "{{ username }}"
      shell: /usr/bin/zsh
