---
- name: install required packages
  package:
      name:
        - curl
      state: latest

- name: install oh-my-zsh
  become_user: "{{ account.name }}"
  shell: 
      cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --keep-zshrc"
      creates: "{{ account.home }}/.oh-my-zsh"

