---    
- name: install required packages
  package:
      name:
        - git
        - git-flow
      state: latest

- name: install git config
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/git"
      cmd: ./install.sh
      creates: "{{ account.home }}/.gitconfig"

