---
- name: install common tools
  package:
      name:
        - tree
      state: latest

- name: install debian tools
  package:
      name:
        - aptitude
      state: latest
  when: ansible_facts["os_family"] == "Debian"
