---
- name: install common tools
  package:
      name: "{{ item }}"
      state: latest
  loop:
    - tree
    - unzip
    - yarn

- name: install debian tools
  package:
      name: "{{ item }}"
      state: latest
  loop:
    - aptitude
  when: ansible_facts["os_family"] == "Debian"
