---    
- name: install required packages
  package:
      name:
        - tmux
      state: latest

- name: install tmux plugin manager
  become_user: "{{ account.name }}"
  git:
      repo: https://github.com/tmux-plugins/tpm.git
      dest: "{{ account.home }}/.tmux/plugins/tpm"
      accept_hostkey: yes
      update: no

- name: install tmux config
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/tmux"
      cmd: ./install.sh
      creates: "{{ account.home }}/.tmux.conf"

