---
- name: install packages
  package:
      name: 
        - docker
        - docker-compose
      state: latest

- name: activate daemon
  systemd:
      name: docker
      enabled: yes
      state: started

- name: add user to docker group
  user:
      name: "{{ account.name }}"
      groups: docker
      append: yes

