---    
- name: install os packages
  package:
      name:
        - cmake
        - llvm
        - clang
        - python-pip
      state: latest

- name: install python packages
  become_user: "{{ account.name }}"
  pip:
      name: 
        - conan
        - python-language-server
      state: latest
      extra_args: --user
