---
- name: setup user account
  user:
      name: "{{ username }}"
      password: "{{ password }}"
      generate_ssh_key: yes
      create_home: yes
      state: present
      update_password: always
  register: account
