---    
- name: install basic packages
  package:
      name:
        - aptitude
        - git
        - tmux
        - tree
      state: latest

- name: clone dotfiles
  become_user: "{{ account.name }}"
  git:
      repo: git@github.com:mandlm/dotfiles.git
      dest: "{{ dotfiles }}"
      accept_hostkey: yes
      update: no

- name: install zsh config
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/zsh"
      cmd: ./install.sh
      creates: "{{ account.home }}/.zshrc"
  
- name: install tmux plugin manager
  become_user: "{{ account.name }}"
  git:
      repo: https://github.com/tmux-plugins/tpm.git
      dest: "{{ account.home }}/.tmux/plugins/tpm"
      accept_hostkey: yes
      update: no

- name: install tmux config
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/tmux"
      cmd: ./install.sh
      creates: "{{ account.home }}/.tmux.conf"

- name: install git config
  become_user: "{{ account.name }}"
  shell:
      chdir: "{{ dotfiles }}/git"
      cmd: ./install.sh
      creates: "{{ account.home }}/.gitconfig"

